const toCyrillic = text => text
  .replace(/lj/g, 'ль')
  .replace(/Lj/g, 'Ль')
  .replace(/LJ/g, 'Ль')
  .replace(/nj/g, 'нь')
  .replace(/Nj/g, 'Нь')
  .replace(/NJ/g, 'Нь')

  .replace(/a/g, 'а')
  .replace(/b/g, 'б')
  .replace(/c/g, 'ц')
  .replace(/č/g, 'ч')
  .replace(/ć/g, 'ћ')
  .replace(/d/g, 'д')
  .replace(/đ/g, 'ђ')
  .replace(/e/g, 'е')
  .replace(/ě/g, 'ѣ')
  .replace(/f/g, 'ф')
  .replace(/g/g, 'г')
  .replace(/h/g, 'х')
  .replace(/i/g, 'и')
  .replace(/y/g, 'ы')
  .replace(/j/g, 'ј')
  .replace(/k/g, 'к')
  .replace(/l/g, 'л')
  .replace(/m/g, 'м')
  .replace(/n/g, 'н')
  .replace(/o/g, 'о')
  .replace(/p/g, 'п')
  .replace(/r/g, 'р')
  .replace(/s/g, 'с')
  .replace(/ś/g, 'сь')
  .replace(/š/g, 'ш')
  .replace(/t/g, 'т')
  .replace(/u/g, 'у')
  .replace(/v/g, 'в')
  .replace(/z/g, 'з')
  .replace(/ź/g, 'зь')
  .replace(/ž/g, 'ж')

  .replace(/A/g, 'А')
  .replace(/B/g, 'Б')
  .replace(/C/g, 'Ц')
  .replace(/Č/g, 'Ч')
  .replace(/Ć/g, 'Ћ')
  .replace(/D/g, 'Д')
  .replace(/Đ/g, 'Ђ')
  .replace(/E/g, 'Е')
  .replace(/Ě/g, 'Ѣ')
  .replace(/F/g, 'Ф')
  .replace(/G/g, 'Г')
  .replace(/H/g, 'Х')
  .replace(/I/g, 'И')
  .replace(/Y/g, 'Ы')
  .replace(/J/g, 'Ј')
  .replace(/K/g, 'К')
  .replace(/L/g, 'Л')
  .replace(/M/g, 'М')
  .replace(/N/g, 'Н')
  .replace(/O/g, 'О')
  .replace(/P/g, 'П')
  .replace(/R/g, 'Р')
  .replace(/S/g, 'С')
  .replace(/Ś/g, 'Сь')
  .replace(/Š/g, 'Ш')
  .replace(/T/g, 'Т')
  .replace(/U/g, 'У')
  .replace(/V/g, 'В')
  .replace(/Z/g, 'З')
  .replace(/Ź/g, 'Зь')
  .replace(/Ž/g, 'Ж')

module.exports = {
  toCyrillic,
}
